### ISSUE TITLE
Podrška za više događaja (sajmova)

### ISSUE THREAD

**Issue by zstapic** [AIR-FOI-HR/AIR1903#89]
U sustavu dodati mogućnost kreiranja novog događaja. Na početnoj stranici ili negdje se odabere događaj, i onda sve ostale opcije upravljanja se odnose samo na taj događaj. Novi korisnici i nove trgovine se automatski pridružuju posljednjem kreiranom događaju.

**Comment by zstapic** [comment]
- [ ] Ažuriranje baze podataka
- [ ] Omogućiti odabir događaja (kod izbornika ili na glavnoj stranici)
- [ ] Omogućiti pregled/promjenu/dodavanje/brisanje događaja
- [ ] Omogućiti prikaz/upravljanje korisnika samo za odabrani događaj
- [ ] Omogućiti prikaz/upravljanje svih ostalih sadržaja samo za odabrani događaj
- [ ] Složiti prikaz izvješća samo za odabrani događaj
- [ ] Nove korisnike koji se registriraju dodijeliti u posljednji događaj
- [ ] Nove ostale sadržaje koji se kreiraju kroz web sučelje dodijeliti u odabrani događaj
