### ISSUE TITLE
Registracija novih korisnika

### ISSUE THREAD

**Issue by zstapic** [AIR-FOI-HR/AIR1903#90]
Kod registracije novih korisnika potrebno je omogućiti da se pri registraciji odabere uloga korisnika (trgovac ili kupac). Za trgovca je potrebno složiti da odmah unese naziv trgovine, a za kupca da odabere jednu od postojećih trgovina.

**Comment by zstapic** [comment]
- [ ] Izmijeniti API kako bi se kod registracije moglo poslati podatke o tipu korisnika
- [ ] Izmijeniti API kako bi se kod registracije trgovca moglo poslati naziv nove trgovine
- [ ] Izmijeniti API kako bi se kod registracije kupca moglo poslati ID postojeće trgovine u koju pripada 
- [ ] Provjeriti/Dodati API koji vraća sve trgovine koji treba za mobilnu aplikaciju.
- [ ] Izmijeniti proces registracije kod mobilne aplikacije da se omogući odabir tipa korisnika
- [ ] Izmijeniti proces registracije kod mobilne aplikacije da se nakon odabira trgovca zatraži unos naziva trgovine
- [ ] Izmijeniti proces registracije kod mobilne aplikacije da se nakon odabira kupca zatraži odabir postojeće trgovine (spajanje na web servis)
- [ ] Izmijeniti algoritam registracije kod mobilne aplikacije da se svi relevantni podaci pošalju na novi API.
