### ISSUE TITLE
Prikaz/upravljanje računima

### ISSUE THREAD

**Issue by zstapic** [AIR-FOI-HR/AIR1903#92]
Kod prikaza i upravljanja postojećim računima potrebno je napraviti manje izmjene koje se odnose na pretragu i detaljan pregled.

**Comment by zstapic** [comment]
- [ ]  Osigurati da se prikazuju računi samo aktivnog događaja.
- [ ] Osnovni (default) pogled neka ima paginaciju od 500+ zapisa.
- [ ] Omogućiti pretragu računa po svim kriterijima uključujući vrijeme, kupca, prodavača, trgovinu i što već...
