### ISSUE TITLE
Kupovina vlastitih proizvoda

### ISSUE THREAD

**Issue by zstapic** [AIR-FOI-HR/AIR1903#93]
Mobilnu aplikaciju je potrebno izmijeniti na način da se onemogući kupovina vlastitih proizvoda. S tim u vezi i web aplikaciju je potrebno izmijeniti na način da se i kupce može svrstati u trgovinu. To bi već trebalo biti riješeno kod registracije (#90), a ovim taskom bi smo riješili i ostale vezane zahtjeve.

**Comment by zstapic** [comment]
- [ ] Provjeriti da podatkovni model omogućuje ovu funkcionalnost
- [ ] Provjeriti da se svi korisnici svrstavaju u trgovinu odmah pri registraciji
- [ ] Složiti da nisu svi prodavači koji su članovi trgovine (mislim da je tako trenutno)
- [ ] Složiti da se preko weba za svakog kupca vidi u kojoj je trgovini i da se to može izmijeniti
- [ ] Složiti na mobitelu da se onemogući transakcija unutar iste trgovine
